### ISSUE TITLE
Implement "filter blurb" and "homepage blurb" in the theme

### ISSUE THREAD

**Issue by moui72** [openlab-at-city-tech/webworkqa#60]
Filter blurb (goes in the blue box above the dropdowns)

```
Use the 
<a href="http://openlabdev.org/webwork-playground/help/explore-existing-questions-and-replies/#filter">filters</a> 
below to navigate the questions that have been posted. You can select questions by course, section, 
a specific WeBWorK problem set, and to select only answered or unanswered questions.`
```

Homepage blurb (goes at the top of the questions index)

```
You are viewing 
<a href="http://openlabdev.org/webwork-playground/about/">WeBWorK on the OpenLab</a>. 
Here, you can ask questions and discuss WeBWorK homework problems, and also see what other 
students have been asking.
```

**Comment by boonebgorges** [comment]
At some point in the future, I'll make these dynamic. For now, I've changed them in the hardcoded text.

**Comment by boonebgorges** [comment]
Given the emerging theme-independence of the plugin and theme, we should reassess this enhancement. The current state of things is that each of these blurbs has default text (non-OL-specific) hardcoded into the plugin, and the text can be filtered using custom PHP code (as we've done on the OL to introduce OL-specific language). 

I think this is probably a good-enough solution for release. It doesn't make a ton of sense to move it into webwork-theme, since the blurbs appear within the content area, and the content area is theme-independent. And because the text is generic and not OL-specific, it's likely that it'll be good enough for most installations, and the PHP filters provide a way to modify for those who really need to do so.
